name: Release
on:
  push:
    branches:
      - master
      - next

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          version: 16.x

      - name: Install Dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@main
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
